from django.urls import path, re_path
from .views import (
    landing_page,
    shoe_finder,
    summary,
    results,
    update_foot,
    filter_shoes,
    get_model_color,
    profile,
    delete_account,
    change_email,
    change_name,
    ModelAutocomplete,
    set_list_layout,
    set_grid_layout
)
from .admin import ShoeColorAutocomplete


urlpatterns = [
    path(
        '', 
        landing_page, 
        name='landing_page'
    ),
    path(
        'shoe-finder/', 
        shoe_finder, 
        name='shoe_finder'
    ),
    path(
        'shoe-finder/<str:step>/', 
        shoe_finder, 
        name='shoe_finder'
    ),
    path(
        'results/', 
        results, 
        name='results'
    ),
    path(
        'update-foot',
        update_foot,
        name='update_foot'
    ),
    path(
        'summary/',
        summary,
        name='summary'
    ),
    path(
        'results/filter-shoes/',
        filter_shoes,
        name='filter_shoes'
    ),
    path(
        'results/filter-shoes/<int:page>/',
        filter_shoes,
        name='filter_shoes'
    ),
    path(
        'get-model-color/<str:model_name>&<str:color>/', 
        get_model_color, 
        name='get_model_color'),
    path(
        'profile/', 
        profile, 
        name='profile'
    ),
    path(
        'accounts/delete/account/', 
        delete_account, 
        name='delete_account'
    ),
    path(
        'accounts/change/email/', 
        change_email, 
        name='change_email'
    ),
    path(
        'accounts/change/name/', 
        change_name, 
        name='change_name'
    ),
    re_path(
        r'^model-autocomplete/$', 
        ModelAutocomplete.as_view(), 
        name='model_autocomplete'
    ),
    path(
        'set-list-layout/',
        set_list_layout,
        name='set_list_layout'    
    ),
    path(
        'set-grid-layout',
        set_grid_layout,
        name='set_grid_layout'    
    )
]